:last-update-label!:
:icons: font
:toc:

= Einstiegsseite
Lars Hermes <lars@hermes-it-consulting.de>
v1.0, 19.01.2017

Diese Seite dient als Einstieg in eine Dokumentationsstruktur mit AsciiDoc. Es
ist spannend was AsciiDoc alles kann und wie einfach es zu bedienen sein wird!

toc::[]

== Formatierung

In diesem Abschnitt werden erstmal die unterschiedlichen Formatierungsoptionen
von AsciiDoc getestet:

=== Listen

* Unordered Item 1
* Unordered Item 2
* ...

* Main Item
** Sub Item
*** Child Item

Geordnete Listen gibt es selbstverständlich auch:

. Eintrag
. Eintrag
. usw.

Checklisten sind auch möglich:

* [*] checked
* [*] auch
* [ ] diesmal nicht :-p

=== Textformatierung

Dieser Text ist *fett*, dieser ist _kursiv_, #hervorgehoben# und `monospace`

Dokumente lassen sich auch durch horizontale Trenner aufteilen:
'''

TIP: Ich habe eine Idee!

NOTE: Esist wichtig, dass immer eine Leerzeile zwischen den Elementen ist, sonst
werden diese nicht sauber erkannt!

WARNING: Wenn es draußen kalt ist, geh nicht in der Badehose raus!

CAUTION: Barfuß im Schnee führt zu erfrorenen Zehen!

IMPORTANT: Immer schön auf Mutti hören!

== Verlinkungen

Es können externe Links eingefügt werden:

* https://docs.oracle.com/javase/8/docs/api/ - automatische Verlinkung
* https://docs.oracle.com/javase/8/docs/api/[JavaDoc für Java 8] - mit Namen
* link:index.html[dieses Dokument gerendered] - relativ
