:numbered:
:icons: font
:toc:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Einstiegsseite
Lars Hermes <lars@hermes-it-consulting.de>
v1.0, 19.01.2017

Diese Seite dient als Einstieg in eine Dokumentationsstruktur mit AsciiDoc. Es
ist spannend was AsciiDoc alles kann und wie einfach es zu bedienen sein wird!

toc::[]

== Formatierung

In diesem Abschnitt werden erstmal die unterschiedlichen Formatierungsoptionen
von AsciiDoc getestet:

=== Listen

* Unordered Item 1
* Unordered Item 2
* ...

* Main Item
** Sub Item
*** Child Item

Geordnete Listen gibt es selbstverständlich auch:

. Eintrag
. Eintrag
. usw.

Checklisten sind auch möglich:

* [*] checked
* [*] auch
* [ ] diesmal nicht :-p

=== Textformatierung

Dieser Text ist *fett*, dieser ist _kursiv_, #hervorgehoben# und `monospace`

Dokumente lassen sich auch durch horizontale Trenner aufteilen:

'''

TIP: Ich habe eine Idee!

NOTE: Esist wichtig, dass immer eine Leerzeile zwischen den Elementen ist, sonst
werden diese nicht sauber erkannt!

WARNING: Wenn es draußen kalt ist, geh nicht in der Badehose raus!

CAUTION: Barfuß im Schnee führt zu erfrorenen Zehen!

IMPORTANT: Immer schön auf Mutti hören!

== Verlinkungen

Es können externe Links eingefügt werden:

* https://docs.oracle.com/javase/8/docs/api/ - automatische Verlinkung
* https://docs.oracle.com/javase/8/docs/api/[JavaDoc für Java 8] - mit Namen

Interne Referenzen zu <<Formatierung>> sind auch ohne weiteres möglich.

== Embedded Code

=== Direkt

[[app-listing]]
[source,java]
.Hello.java
----
import java.util.*; // <1>

public class Hello { // <2>
  public static void main(String[] args) {
    System.out.println("Hello");
  }
}
----
<1> Library import
<2> Class definition

=== Verwendung eines Sourcefiles

:sourcedir: src/main/java

[source,java]
----
include::{sourcedir}/de/hermes/playground/simple/HelloWorld.java[]
----

[sidebar]
.Ergänzende Informationen
--
Zusätzliche Informationen.

Kann verwendet werden, weitere Informationen hinzuzufügen, z.B.:

<1> Package definition
<2> Class definition
<3> Main method
<4> Prints string to console
--

=== Inline Anweisungen

Installation  von AsciDoc unter Ubuntu:

[listing]
sudo apt-get install asciidoc


== Tabellen

[cols="2*", options="header"]
|===
|Name
|Group

|Firefox
|Web Browser

|Ruby
|Programming Language

...
|===

== Zitate

[quote, Albert Einstein]
A person who never made a mistake never tried anything new.

== Eingebettete Dokumente

Das ist ein separates Dokument, das hier inklusive seiner Formatierung eingebunden wird.

include::test.adoc[]
